#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global user.email "florian.huckel@epita.fr"
  - git config --global user.name "Mploki"

# clone directory
clone_folder: C:\projects\testveyor

# environment variables
environment:
  GithubUsername: Mploki

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: npm install sqlite3
  - cmd: npm install bluetooth-serial-port
  - cmd: npm install phantomjs
  - cmd: npm install mdns

test: off

artifacts:
  - path: src/hello.exe
#cache:
#  - C:\Ruby193\lib\ruby\gems\1.9.1
#  - C:\Ruby193\bin
